## Import all libraries

In [35]:
import os 
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from xgboost import XGBClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import(
    StandardScaler,
    LabelEncoder
)
from sklearn.model_selection import(
    train_test_split,
    StratifiedGroupKFold
)
from sklearn.metrics import (
    accuracy_score,
    recall_score,
    roc_auc_score,
    precision_score,
    PrecisionRecallDisplay,
    RocCurveDisplay,
    ConfusionMatrixDisplay
)

## Load datasets

In [36]:
cwd = os.getcwd()
data_dir_path = os.path.join(cwd, 'data')

df_train, df_test = (
    pd.read_csv(os.path.join(data_dir_path, 'train.csv')).set_index('PassengerId'),
    pd.read_csv(os.path.join(data_dir_path, 'test.csv')).set_index('PassengerId')
)

## EDA

#### Data profiling

In [37]:
df_train.head()

            HomePlanet CryoSleep  Cabin  ... VRDeck               Name Transported
PassengerId                              ...
0001_01         Europa     False  B/0/P  ...    0.0    Maham Ofracculy       False
0002_01          Earth     False  F/0/S  ...   44.0       Juanna Vines        True
0003_01         Europa     False  A/0/S  ...   49.0      Altark Susent       False
0003_02         Europa     False  A/0/S  ...  193.0       Solam Susent       False
0004_01          Earth     False  F/1/S  ...    2.0  Willy Santantines        True

[5 rows x 13 columns]

In [38]:
df_train.info()

<class 'pandas.DataFrame'>
Index: 8693 entries, 0001_01 to 9280_02
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   str
 1   CryoSleep     8476 non-null   object
 2   Cabin         8494 non-null   str
 3   Destination   8511 non-null   str
 4   Age           8514 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8512 non-null   float64
 7   FoodCourt     8510 non-null   float64
 8   ShoppingMall  8485 non-null   float64
 9   Spa           8510 non-null   float64
 10  VRDeck        8505 non-null   float64
 11  Name          8493 non-null   str
 12  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(4)
memory usage: 891.4+ KB

In [39]:
df_train.describe()

               Age   RoomService  ...           Spa        VRDeck
count  8514.000000   8512.000000  ...   8510.000000   8505.000000
mean     28.827930    224.687617  ...    311.138778    304.854791
std      14.489021    666.717663  ...   1136.705535   1145.717189
min       0.000000      0.000000  ...      0.000000      0.000000
25%      19.000000      0.000000  ...      0.000000      0.000000
50%      27.000000      0.000000  ...      0.000000      0.000000
75%      38.000000     47.000000  ...     59.000000     46.000000
max      79.000000  14327.000000  ...  22408.000000  24133.000000

[8 rows x 6 columns]

In [40]:
df_train.dtypes

HomePlanet          str
CryoSleep        object
Cabin               str
Destination         str
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name                str
Transported        bool
dtype: object

In [41]:
df_train.isna().sum()

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [42]:
df_train.duplicated().sum()

np.int64(0)

In [43]:
df_train.head()

            HomePlanet CryoSleep  Cabin  ... VRDeck               Name Transported
PassengerId                              ...
0001_01         Europa     False  B/0/P  ...    0.0    Maham Ofracculy       False
0002_01          Earth     False  F/0/S  ...   44.0       Juanna Vines        True
0003_01         Europa     False  A/0/S  ...   49.0      Altark Susent       False
0003_02         Europa     False  A/0/S  ...  193.0       Solam Susent       False
0004_01          Earth     False  F/1/S  ...    2.0  Willy Santantines        True

[5 rows x 13 columns]

#### Fillin and deleting Nan data

In [44]:
def clean_df(df):
    df_ = df.copy()

    df_ = (df_
        .drop('Name', axis=1)
        .assign(HomePlanet=lambda df__: df__['HomePlanet'].fillna(df__['HomePlanet'].mode()[0]))
        .assign(CryoSleep=lambda df__: df__['CryoSleep'].fillna(df__['CryoSleep'].mode()[0]).astype(int))
        .assign(VIP=lambda df__: df__['VIP'].fillna(df__['VIP'].mode()[0]).astype(int))
    )

    return df_

In [45]:
a = clean_df(df_train)

In [46]:
a.head()

            HomePlanet  CryoSleep  Cabin  ...     Spa  VRDeck  Transported
PassengerId                               ...
0001_01         Europa          0  B/0/P  ...     0.0     0.0        False
0002_01          Earth          0  F/0/S  ...   549.0    44.0         True
0003_01         Europa          0  A/0/S  ...  6715.0    49.0        False
0003_02         Europa          0  A/0/S  ...  3329.0   193.0        False
0004_01          Earth          0  F/1/S  ...   565.0     2.0         True

[5 rows x 12 columns]